name: crypto_exchange_runners
description: A starting point for Dart libraries or applications.
version: 0.0.1
#homepage: https://www.example.com
#author: Mike <email@example.com>

environment:
  sdk: '>=1.20.1 <2.0.0'


dependencies:
  path: ^1.4.1
  request_throttler:
    git: https://github.com/bearcrypto/request_throttler.git
  crypto_exchange_model:
    git: https://github.com/bearcrypto/crypto_exchange_model.git

dev_dependencies:
  test: ^0.12.0
